spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/beta?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
#    password: EhgusEjrgus123!
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update
  freemarker:
    cache: false
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
livereload:
  enabled: true




